### ISSUE TITLE
ddev.exe didn't copy on Windows 10 Pro (missing %HOMEPATH%)

### ISSUE THREAD

**Issue by mradcliffe** [drud/quicksprint#1]
## What happened (or feature request):

Running .\install_ddev.cmd from the following places:

1. Using Docker QuickStart Terminal (Git Bash included with Docker ToolBox):
   * `cd /c/Users/username/Desktop/drupal_sprint_package`
   * `./install_ddev.cmd`
   * Error: `C:\Users\username\Desktop\drupal_sprint_package\ddev_tarballs>copy ddev.exe \\AppData\Local\Microsoft\WindowsApps The network path was not found.`
2. Using PowerShell (since I'm on Windows 10 Pro):
   * `cd C:\Users\username\Desktop\drupal_sprint_package`
   * `.\install_ddev.cmd`
   * `C:\Users\username\Desktop\drupal_sprint_package\ddev_tarballs>copy ddev.exe \\AppData\Local\Microsoft\WindowsApps The network path was not found.`
3. Double-click install_ddev.cmd
   * Didn't copy.

Manually copying into the correct location works as a workaround.

## What you expected to happen:

`%HOMEPATH%` is expanded to the correct path.

## How to reproduce this:

Windows 10 Pro
Docker ToolBox

## Version:

0.0.2

**Comment by rfay** [comment]
Ah shoot, lots of things don't work with network paths.  Nothing works in CMD. I think we've seen this before when people tried to use a home directory that was in a network path.

**Comment by rfay** [comment]
This is obsolete now that we have a windows installer.
