### ISSUE TITLE
Move build to Travis/Circle CI? Releases?

### ISSUE THREAD

**Issue by rickmanelius** [drud/quicksprint#10]
This is a stub. While this can be run locally to build out the assets, what about tying this to CircleCI where people can then download assets there? What about releases against this project?

This is not urgent. I'm chatting with @mradcliffe and I think this might be a good mechanism once we have determined if this repo is going to be used longterm.

**Comment by BrianGilbert** [comment]
If we can make it build the archives generated by package_drupal_sprint script and create the release with them linked, that would save me the hassle of trying to upload it from Australia

**Comment by mradcliffe** [comment]
We would need to split the releases into MacOS, Windows and Linux versions since GitHub's Release API will fail if you upload more than 1gb (it kind of works).

**Comment by mradcliffe** [comment]
This is done and can be closed.

**Comment by rfay** [comment]
Closing, we'll do even more with it in the future.
