### ISSUE TITLE
ddev start does not provide me a link like the instructions says it would

### ISSUE THREAD

**Issue by cosmicdreams** [drud/quicksprint#123]
Platform: MacOS Mojave

I attempted to install this for the first time on my laptop and couldn't get past the ```ddev start``` part that I assume is near the end of the process.  I have installed Docker and used it before on my laptop without issue but I had never used a ddev instance before.

I'm going to let the process go for a long as I can to see if it'll eventually complete.  It's been going for more than 40 minutes so far and it's either not done or stalled.

**Comment by rfay** [comment]
Could you please provide the actual output that you saw?  I assume you didn't install docker from the tarball. Please try the "see if docker is working" command from https://ddev.readthedocs.io/en/stable/users/docker_installation/#testing-and-troubleshooting-your-docker-installation: `docker run --rm -t -p 80:80 -v "/$PWD:/tmp/projdir" -v "/$HOME:/tmp/homedir" busybox sh -c "echo ---- Project Directory && ls //tmp/projdir && echo ---- Home Directory && ls //tmp/homedir"` - the output should show your project directory and home directory contents.

**Comment by cosmicdreams** [comment]
Sure:

```
cweber-osx:drupal_sprint_package cweber$ cd ~/sprint/
cweber-osx:sprint cweber$ ./start_sprint.sh 
Untarring sprint.tar.xz
docker is running, continuing.Using ddev version v1.6.0 from /usr/local/bin/ddev
Creating a new ddev project config in the current directory (/Users/cweber/sprint/sprint-20190327-1525) 
Once completed, your configuration will be written to /Users/cweber/sprint/sprint-20190327-1525/.ddev/config.yaml
 
Found a drupal8 codebase at /Users/cweber/sprint/sprint-20190327-1525/drupal8 
Ensuring write permissions for sprint-20190327-1525 
No settings.php file exists, creating one 
Existing settings.php file includes settings.ddev.php 
Configuration complete. You may now run 'ddev start'. 
Configuring your fresh Drupal8 instance. This takes a few minutes.
Running ddev start...
```

I eventually came back to this after closing my laptop for the day and getting back online and noticed that it finally processed through and was waiting for me to enter a password.  I'm pretty sure it wasn't asking me for a password before.  But there's always the case that I didn't see the part of the process that was waiting for me to enter some input.  

Maybe this isn't an issue after all.

**Comment by rfay** [comment]
My bet is it was waiting for the password. Do you have a suggestion about how we can make that clearer? Of course with guides/mentors reminding people it will happen it won't be a problem but if you got derailed by it you won't be the only one.

`ddev start` actually only takes about 11 seconds on average on a current MBP... Of course there are things that happen after that (updating the git checking, doing a composer install) that take a little time.

**Comment by cosmicdreams** [comment]
My only thought here is that I bet was that thing that happens with Terminal sometimes when you accidentally scroll up on the text and the bottom of the window is obscured.  

Maybe:
1. Warn the user (before the long process of loading) that they might have to enter a password in order to allow the process to complete.

Yeah I thought I had more suggestions but I don't

**Comment by cosmicdreams** [comment]
Good news is that I'll be one of the mentors on Sprint day.  Now that this has happened to me, I'll be on the lookout for it happening on that day

**Comment by rfay** [comment]
This problem may be a result of the instrumentation opt-in prompt that happens on first ddev usage (and has been added since last time around on quicksprint). If we do a `ddev config global --instrumentation-opt-in=false` before the `ddev start` it would prevent that prompt from appearing.

Also, the `ddev start` output is redirected in the start_sprint.sh command, which is probably a mistake, and may be involved with this.
