### ISSUE TITLE
Docker Toolbox must be restarted to properly configure the ddev_default network (Windows 10 Home)

### ISSUE THREAD

**Issue by andrewfrench** [drud/quicksprint#126]
On a Quicksprint install flow and using a fresh Windows 10 Home machine (no previous Docker or ddev installation), start_sprint.sh fails after installing Docker Toolbox and running install.sh.

The start_sprint.sh process fails while trying to fetch the current Drupal8 git repository because the web container does not have access to the Internet. Bypassing this by running the git commands on the host leads to the `ddev composer install` step failing as composer assets cannot be downloaded.

A workaround for this is to restart Docker after install.sh has completed. I'm not certain how feasible it is to restart Docker itself during the execution of install.sh, but that could be one way to solve the problem.

**Comment by rfay** [comment]
I'm completely unable to recreate this problem. I started on a Win 10 Home machine by
* Made sure the firewall was on
* docker-machine stop
* docker-machine rm default
* Uninstall docker toolbox from the Windows "Add or remove Programs"
* Install docker toolbox again
* `ddev composer install` in a Drupal project. It started downloading composer-things right away.

**Comment by rfay** [comment]
I was unable to recreate this starting with a fresh install of Windows 10 Home, so I think we're going to have to punt for now. Good experience for me though!  @andrewfrench if you think it's important enough to chase point me the right direction. But I think this is probably not going to be a big issue.

**Comment by rfay** [comment]
Closing for now, will keep eyes open.
