### ISSUE TITLE
xz not found at start sprint step

### ISSUE THREAD

**Issue by dtw2000** [drud/quicksprint#129]
xz not found at start sprint step

Output:
$ ./start_sprint.sh
Untarring sprint.tar.xz
tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

**Comment by rfay** [comment]
Are you using quicksprint or what they're handing out at Drupalcon? (a fork, unknown lineage)? What OS are you on? Regardless, if Windows, you may want to make sure you have the latest git-for-windows, which includes xz.

**Comment by andrewfrench** [comment]
~Based on your error output, it looks like you may be running the source code version of the Quicksprint, is that right? I get a similar error if I run `./start_sprint.sh` on the master branch because the repository doesn't include the artifacts the scripts expect.~

~If that's the case, try starting a sprint using the appropriate distribution for your environment, [available here](https://github.com/drud/quicksprint/releases/tag/v1.0.1).~

Whoops, I misunderstood that error message. Randy's answer is more relevant to the issue.

**Comment by rfay** [comment]
@dtw2000 I'm pretty sure you'll find (if on Windows) that you need to install the current git for windows. If you're on another OS, let us know and we'll guide you. Most macOS/Linux systems are all set with xz.

**Comment by dtw2000** [comment]
@rfay I'm at druppalCon and was attempting to run this on Windows.  Brian Gilbert, maybe - I'm not sure, was super nice and was trying to help me get it running.  We posted the error and he recommended I reach out to you on the drupal slack channel, so I'll reach out to you there.  I wanted to try again first.

At first, I was using the instructions from https://www.drupal.org/tools#windows
After a bit, we tried downloading from git https://github.com/drud/quicksprint/releases/download/v1.0.1/drupal_sprint_package.no_extra_installs.v1.0.1.zip and running that.
A bit later, we were looking through the install.sh and trying to manually follow the script.  We were using 'git bash' 

I'm a noob, and not entirely sure how to recreate the error, but I'll describe as best as I can what I'm trying.

If I run 'git bash' > cd to the install.sh directory and try to run 'install.sh' ...
***@*** ~/Resilio Sync/Community Tools Windows/drupal_sprint_package
$ install.sh
bash: install.sh: command not found

If I run windows bash and cd to the install.sh and run that, it'll trigger a 'git bash' window and continue
...
Installing docker images for ddev to use...
Loaded image: drud/phpmyadmin:v1.6.0
Loaded image: drud/ddev-ssh-agent:v1.6.0
Loaded image: drud/ddev-router:v1.6.0
Loaded image: drud/ddev-webserver:v1.6.0
Loaded image: drud/ddev-bgsync:v1.6.0
Loaded image: drud/ddev-dbserver:v1.6.0-10.2
####
# This package includes an editor.
# If you already have an editor or IDE, type N here.
####Load Cloud9 IDE? (y/n):y
It does a line of stuff then disappears.

At some point, we manually found an xz executable for windows, put it and associated files in the working directory of the sprint folder trying to manually step through the steps of the script.  The output was from that I think, but I can't seem to get it again.

I'll try again and follow up.

**Comment by rfay** [comment]
Sorry @dtw2000, the Cloud9 IDE is not a part of this package. You'll have to check with @BrianGilbert for support. We don't have any idea about the forked package is that's being distributed there with Cloud9 in it; it was a big surprise.

**Comment by BrianGilbert** [comment]
@rfay we experienced this with the current release of dev downloaded from the quick sprint releases page

**Comment by rfay** [comment]
Right, as above, this is a result of not using current git for windows, which bundles xz.

**Comment by dtw2000** [comment]
@rfay I did uninstall and reinstall the latest git for windows.  Based on your comment, that would explain why I couldn't reproduce it later.  At any rate, thank you both.

**Comment by rfay** [comment]
👍
