### ISSUE TITLE
Support TYPO3 cms on quicksprint

### ISSUE THREAD

**Issue by cyberswat** [drud/quicksprint#13]
We have had requests to support TYPO3 in addition to the default drupal 8.  This request would also apply to the other CMSs supported by DDEV, but we've been asked about TYPO3 first.

**Comment by horncologne** [comment]
TYPO3 CMS core team is getting together 2018.Mar.15 for a sprint. They can get people up to speed using the T3C quickstart docs, which were recently updated. Can we make Sprint-in-a-pocket USB installation stick for TYPO3 CMS happen in time?

**Comment by rfay** [comment]
Wonderful! Might be able to do it.

**Comment by rfay** [comment]
I assume you'd want latest TYPO3 checked out to start?

core team probably has different requirements from a normal public sprint, where people are just learning about everything. 

The reality the existing package would probably do the job with dev pros like that, it just does a bit more than you need by preparing a drupal install. I'll take a look.

**Comment by horncologne** [comment]
Thanks, @rfay. I'm hooking you up with a sprint lead in T3 Slack ...

**Comment by rfay** [comment]
Discussion in slack discovered that this is not needed for the core sprint this week, which has just 10 people. DevDays this summer will be a better candidate. So this can hibernate for a while.

**Comment by rickmanelius** [comment]
Perfect. That certainly helps scope/prioritize things a bit. For 10 individuals, it should be pretty easy to simply walk through the installation and quick start guides as long as bandwidth isn't an issue. Thanks for helping, @rfay!

**Comment by mradcliffe** [comment]
I think it makes sense at this point to move packaging script to a scripts directory, and then have one named for each CMS/project.

Then CI/manual packager can package releases for various sprint tools needed for sprint leads of different CMSes? For instance in Travis, we could add the following. 

```
env:
  - PACKAGE_SCRIPT=scripts/package_drupal.sh
  - PACKAGE=scripts/package_typo3.sh
  # - PACKAGE=scripts/package_wp.sh
```

There probably is an equivalent thing in Circle.

**Comment by rfay** [comment]
Works for me @mradcliffe . However, we will now be able to let the Drupal version mature for a bit before doing anything more.

**Comment by mradcliffe** [comment]
Probably the first step to take for this is to become familiar with the amazingly [TYPO3 Contribution Guide](https://docs.typo3.org/typo3cms/ContributionWorkflowGuide/Index.html) to identify things to automate (really big shout to those [contributors](https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-ContributionWorkflow/graphs/contributors)).

1. [Setting up your git environment](https://docs.typo3.org/typo3cms/ContributionWorkflowGuide/Setup/Git/Index.html) has a bunch of gitconfig that can be automated. This is similar to #83.
2. [Setup the TYPO3 installation](https://docs.typo3.org/typo3cms/ContributionWorkflowGuide/Setup/SetupTypo3.html) references composer and yarn (grunt, bower). I think nodejs is already in the web container.
3. [Testing the Core](https://docs.typo3.org/typo3cms/ContributionWorkflowGuide/Testing/Index.html) mentions a dedicated docker image for running unit, functional and acceptance tests.
4. [Setting up TYPO3 with DDEV](https://docs.typo3.org/typo3cms/ContributionWorkflowGuide/Appendix/SettingUpTypo3Ddev.html) has several steps that can be automated in a start/clean sprint script.

But also need to document how new contributors get setup at an TYPO3 Contribution/Sprint event.

Finally, I think that with a list of differences, it might be possible to have a manifest that could be abstracted into install and start scripts (in contrast to my comment above in March).

**Comment by rfay** [comment]
nodejs and yarn are in fact in the web container. 
Thanks for looking at this!

**Comment by rfay** [comment]
Followups from TYPO3 slack:

* For creating db (dynamically) [Use typo3 console](https://typo3.slack.com/archives/C8TRNQ601/p1547791778234500?thread_ts=1547771521.234300&cid=C8TRNQ601) to build the db. May or may not work. 

>Most people use https://github.com/TYPO3-Console/TYPO3-Console I think, which supports a scripted installation. Don't know if such a thing is also available in core now, after migrating to symphony commands

* For creating db [just use a static db dump and load it](https://typo3.slack.com/archives/C8TRNQ601/p1547796418235600) like we used to do for Drupal. 

* Make sure to [set up according to community guidelines](https://typo3.slack.com/archives/C8TRNQ601/p1547796726236700), 
> Especially the git hooks https://docs.typo3.org/typo3cms/ContributionWorkflowGuide/Setup/Git/Index.html#setting-up-your-git-environment

**Comment by rfay** [comment]
> @helhum did a great job to boost a typo3 site without any manipulation : https://github.com/helhum/ddev-typo3 ([slack](https://typo3.slack.com/archives/C8TRNQ601/p1547842238245700?thread_ts=1547771521.234300&cid=C8TRNQ601))

**Comment by mradcliffe** [comment]
I'm also working something related, but on the Drupal end. To be able to provide/add back in the IDE container (optionally as both a build and a user preference). So storing Drupal/Typo3 specific configuration is an aspect of this.

**Comment by rfay** [comment]
There hasn't been any more interest that I can determine from the TYPO3 end. It seems they just teach everybody to use ddev from the start, so don't need this extra. Closing.
