### ISSUE TITLE
Reached github releases file size limit of 2GB for full package

### ISSUE THREAD

**Issue by rfay** [drud/quicksprint#134]
Due to the growing size of the Docker installers for Windows and macOS, the "full" tarball got too big, and now github won't let it go to the releases page; they have a limit of 2GB. 

There's a pretty simple solution to this: Package the installers as a separate tarball/zipball file. And it's a reasonable thing to do as well. 

As a result of this the full tarball for v1.1.0 is available at https://circleci.com/gh/drud/quicksprint/1550#artifacts/containers/0 but not on the releases page, https://github.com/drud/quicksprint/releases/tag/v1.1.0

**Comment by mradcliffe** [comment]
Also could make a tarball for each OS, but I think that could be more confusing. I've done that before.

**Comment by rfay** [comment]
good point, thanks
