### ISSUE TITLE
Intermittent failure on nightly build

### ISSUE THREAD

**Issue by rfay** [drud/quicksprint#159]
The nightly build is broken. I haven't investigated it yet. For example, https://circleci.com/gh/drud/quicksprint/1977

**Comment by mradcliffe** [comment]
I ran the tests this morning locally on MacOS, and didn't run into any issues.

Might need to add some debug statements in test setup and see what happens.

**Comment by mradcliffe** [comment]
Hmm, a PR just passed the test suite with only minimal changes, so that rules out debugging. Maybe wait another nightly cycle.

**Comment by rfay** [comment]
Looks like perhaps there's a difference between the nightly and regular build?

Also, I note that I've seen the nightly build failure intermittently before, it seems to have to do with something fragile in the site setup.  Note in https://circleci.com/gh/drud/quicksprint/1977?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link that 

>  Failed to start sprint-20191111-0346: web container failed: log=, err=container exited, please use 'ddev logs -s web` to find out why it failed
> ddev start failed.Failed to get project(s): Could not find a project in /home/circleci/sprint. Have you run 'ddev config'? Please specify a project name or change directories: no .ddev/config.yaml file was found in this directory or any parent

But "no .ddev/config.yaml was found in ~/sprint! That means the script did something stupid either in setup or something, because it shouldn't have been in that directory. And I've seen this sporadically before.

**Comment by mradcliffe** [comment]
> But "no .ddev/config.yaml was found in ~/sprint! That means the script did something stupid either in setup or something, because it shouldn't have been in that directory. And I've seen this sporadically before.

I think that's due to it failing before test completion so it doesn't have a chance to change directory into `${SPRINTDIR}/${SPRINT_NAME}/drupal8` directory.

**Comment by rfay** [comment]
That makes sense, so it's trying to take down something that it never got going? That should be a fairly easy fix.  (But we see the `ddev start` fail... So it must have gotten in there...)

**Comment by mradcliffe** [comment]
The nightly test_package succeeded today - https://circleci.com/gh/drud/quicksprint/1983

**Comment by rfay** [comment]
Has succeeded a couple of times now. This is an old frenemy, so will come back again. I don't mind so much that it fails from time to time, sure wish the flaw in cleanup wasn't there.

**Comment by rfay** [comment]
THis (was) regularly succeeding, so I'll close this one. 

The annoying thing is that test failure results in a wrong takedown in the tests, which is why we see "no .ddev/config.yaml was found in ~/sprint!", I'm pretty sure that's just a symptom of the random failure, not a cause.
