### ISSUE TITLE
Chocolatey failing on Windows Docker CE and Toolbox buildkite

### ISSUE THREAD

**Issue by mradcliffe** [drud/quicksprint#161]
Seemingly simple PR that didn't change anything buildkite or Windows related failed so something is different about chocolatey or the Windows environments:

`ERROR: Cannot bind argument to parameter 'Path' because it is null.` in  `C:\ProgramData\chocolatey\lib\php\tools\chocolateyInstall.ps1'.`

**Comment by rfay** [comment]
Maybe you could say more about this. Did you have trouble with Chocolatey install on v1.12.0? I've done an awful lot of installs via Choco. If you're able to recreate it, please give full instructions. Lots of people are using it.

It looks like you're having trouble installing php?

Oh, or is this the thing that's currently breaking the nightly build. It didn't have anything to do with your PR.

**Comment by rfay** [comment]
Oh, I see you were talking about this in the build log on Windows:
```
php v7.4.0 [Approved]
  | php package files upgrade completed. Performing other installation steps.
  | Uninstalling previous version of php...
  | ERROR: Cannot bind argument to parameter 'Path' because it is null.
  | The upgrade of php was NOT successful.
  | Error while running 'C:\ProgramData\chocolatey\lib\php\tools\chocolateyInstall.ps1'.
  | See log for details.
 ```

It looks like this is not a new issue at all, see https://github.com/chocolatey/choco/issues/1574#issuecomment-441304374

Looks like if we're going to let the windows buildkite upgrade php, it has to be uninstalled first.
