### ISSUE TITLE
install.sh could do silent install of ddev on Windows

### ISSUE THREAD

**Issue by rfay** [drud/quicksprint#171]
Currently install.sh shows the ddev privilege escalation dialog, and it probably doesn't have to. The install could most likely do a silent install, at least in a privileged git-bash window.

**Comment by mradcliffe** [comment]
I think it's appropriate to warn people about privilege escalation although some people do try to ignore / cancel out of it and act surprised. I guess that should be weighed against opening up the complexity of opening a privileged git-bash window, which is more than just using the context menu to "Git Bash Here" or double-clicking Git-Bash on the desktop.

**Comment by rfay** [comment]
I think this is OK as is. Thanks for the comment @mradcliffe
