### ISSUE TITLE
Stop support for Docker Toolbox

### ISSUE THREAD

**Issue by rfay** [drud/quicksprint#174]
Now that Windows Spring release for 2020 is out (Windows 2004), Docker Desktop for Windows runs on Win10 Home, and very nicely.

I think we should stop testing Win10 Toolbox and remove support (and docs)

The path forward for ddev is going to be:

1. Stop testing
2. Deprecate
3. Remove code

Because testing resources are slim (and the same ones used for Quicksprint) I'm quite sure we'll be moving those windows machines to Docker Desktop usage. So that would mean the same for Quicksprint.

**Comment by mradcliffe** [comment]
:+1: That sounds good. It looks like Docker Desktop for Windows Home would be adequate. It requires WSL 2, which is probably the only big hurdle, but hopefully Windows Home users update more frequently than corporate users.

I think the two main blockers for getting rid of Docker Toolbox are probably solved now:

1. local file sharing no longer required
2. Hyper-V no longer required

I had a chance to test on my restricted Windows 10 Pro environment, and it can now run the standard Docker Desktop for Windows.

**Comment by rfay** [comment]
ddev will deprecate docker toolbox in v1.16, so we can just do this after Drupalcon Global and before the next one.
