### ISSUE TITLE
Packaging script may need to include COPYING with docker images, docker, Drupal copyright info

### ISSUE THREAD

**Issue by mradcliffe** [drud/quicksprint#2]
## Feature request:

We may need to include a COPYING file with licenses and copyright for any software we distribute.

## What you expected to happen:

Packaging script should include COPYING file (or keep it in this repository) with the license for this software, ddev, docker, docker images and Drupal.

## Possible example text:

> This Software is distributed in a compressed archive with the following third-party software and Docker images under other copyright notices.
>
>   ddev is included in the distributable release as a software artifact, and is distributed under the Apache 2.0 license:
>
>      ddev - (c) Copyright 2016 DRUD Technology, LLC
> 
>   Docker images are included in the distributable release as software artifacts and distributed according to the provisions of the MIT license:
> 
>     drud/nginx-php-fpm-local - (c) Copyright 2017 DRUD Technology, LLC
>     drud/docker-phpmyadmin - (c) Copyright 2017 DRUD Technology, LLC
>     hoadx/cloud9-alpine - (c) Copyright 2017 hoadx
>     linuxserver/thelounge - (c) Copyright 2016 LinuxServer.io
>
>   Docker images are included in the distributable release as software artifacts and distributed according to the provisions of the Apache 2.0 license:
>
>     drud/ddev-router - (c) Copyright 2016 DRUD Technology, LLC
>     drud/mariadb-local - (c) Copyright 2016 DRUD Technology, LLC
>     mailhog/mailhog - (c) Copyright 2014 - 2017 Ian Kent (http://iankent.uk)
>
>  Drupal is included in the distributable release as a software artifact, and is distributed under the GPL license:
> 
>     Drupal - (c) Copyright 2001 - 2013 by the original authors
>       See drupal/core/COPYRIGHT.txt for more details.
> 
> This Software may be distributed alongside the following third-party software under other copyright notices.
> 
>   Docker Community Edition, or otherwise known as "Docker open source", is distributed under the Apache 2.0 license under the following copyright:
> 
>     Docker open source - (c) 2013 - 2017 Docker, Inc. 
>       See https://www.docker.com/components-licenses for more details.
>

**Comment by rfay** [comment]
This is absolutely necessary, of course. PR is sure welcome.

**Comment by mradcliffe** [comment]
Issue resolved.
