### ISSUE TITLE
Is there anyway to use quicksprint with an established codebase? 

### ISSUE THREAD

**Issue by huy77athe** [drud/quicksprint#201]
Hello, 

I am new to Drupal and I am trying to run my local dev env with an established codebase the quicksprint way. I don't like installing MAMP because I want to make sure I have the same settings when deployed or handling it to other dev. I am not sure if this is the right place to ask this question. Should I use Lando instead of Quicksprint? 

Thank you!

**Comment by mradcliffe** [comment]
You can use [ddev](https://github.com/drud/ddev/) directly to get up and running, @huy77athe.  If you change directory inside your site project, you can run `ddev config` which should start it.


This repository and issue queue is for quicksprint, which is a ddev-based tool used to help people new to contributing to [Drupal core](https://drupal.org/project/drupal).

**Comment by huy77athe** [comment]
Thank you very much for your response! I will close this issue as I think it helped resolve my problem. Thank you!
