### ISSUE TITLE
Add some kind of output to package_drupal_script.sh

### ISSUE THREAD

**Issue by webchick** [drud/quicksprint#22]
I typed ./package_drupal_script.sh a few minutes ago and it's still sitting there. I hope it's ok. :) It would be awesome if there was like a percent completion / progress bar kinda thingy to help assuage my anxiety. :D

**Comment by webchick** [comment]
Ok, the script ran, but no idea what next (I'm sure it's in the docs, which is my next stop). It would also be nice at the end here to have a user-friendly "Such and such thing happened successfully. Now go and $next_step."

**Comment by BrianGilbert** [comment]
Added check for docker running, and more output during creation of packages.
