### ISSUE TITLE
Improve error handling for PEBCAK

### ISSUE THREAD

**Issue by webchick** [drud/quicksprint#23]
Continuing my blindly blundering around (hey, you wanted a realistic user test of a sprint attendee, right? :D)

After I couldn't figure out what to do after running package_drupal_script.sh (see #22), I read through SPRINTUSER_README.md  which talked about running ./install_ddev.sh, which I noticed is in my quicksprint directory. So I did!

Output:

```
Installing docker images for ddev to use...
ls: ddev_tarballs/ddev_docker_images*.tar.xz: No such file or directory
gzip: standard input is a terminal -- ignoring
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
ls: ddev_tarballs/ddev_macos*.tar.gz: No such file or directory
tar: Error opening archive: Failed to open '-C'
chmod: /tmp/ddev: No such file or directory
Ready to place ddev in your /usr/local/bin.
mv: /tmp/ddev: No such file or directory
/usr/local/bin/brew
cp: sprint.tar.xz: No such file or directory


######
#
# Your ddev and the sprint kit are now ready to use, 
# execute the following commands now to start:
#
# cd ~/Sites/sprint
# ./start_sprint.sh
#
######
```

So basically, lots of things catastrophically failed, but I didn't read all of that; instead my eyes focused in on the joyous bright green text that said everything was ready to go. YAY!

So I run the next part:

```
./start_sprint.sh 

tar: Error opening archive: Failed to open 'sprint.tar.xz'
sed: sprint-20180405-0058/.ddev/config.yaml: No such file or directory
sed: sprint-20180405-0058/Readme.txt: No such file or directory
sed: sprint-20180405-0058/start_clean.sh: No such file or directory
sed: sprint-20180405-0058/start_clean.cmd: No such file or directory

######
#
# Your Drupal 8 instance is now ready to use, 
# execute the following commands in terminal 
# to start a Drupal 8 instance to sprint on:
#
# cd sprint-20180405-0058
# ./start_clean.sh
#
######

```

Once again, catastrophic failure, but encouraging green message.

It's only at this point I realize something has screwed up, because there is no "start_clean.sh" script in the sprint-20180405-0058 directory.

Ideally, this would've bailed much sooner than that, with a helpful error that explained what I needed to do to resolve the problem.

**Comment by BrianGilbert** [comment]
Hi @webchick I believe the package for the release you were testing had issues, just in the process of packaging up 0.0.6 that has a lot of improvements.
