### ISSUE TITLE
install_ddev.cmd and install_ddev.sh: Press Y, Press any key

### ISSUE THREAD

**Issue by rfay** [drud/quicksprint#29]
The install_ddev.cmd and install_ddev.sh say

```
"Press Y to continue"
You don't need to press enter!
Press any key to continue.
```

Why that seems like pretty contradictory instructions. I don't know *what* to do.

Is it going to docker install on me? When? (Turns out it asks later, but this is pretty confusing"

**Comment by BrianGilbert** [comment]
Fixed text to say pres anything else to exit, and report out what you did.
