### ISSUE TITLE
install_ddev.cmd fails to run docker install (and doesn't). Must run docker, not just install.

### ISSUE THREAD

**Issue by rfay** [drud/quicksprint#30]
Multiple problems with the install_ddev.cmd and the docker version:

* The install_ddev.cmd fails to find the right docker version (see screenshot)
* The actual provided docker-ce version is 17.09.0, we should be shipping 18.03.0 (#31 - problem on both windows and mac)
* docker must be running for the next step (the ddev installation fails without it). So just installing docker (on windows) is not enough - it must be run.

![failure_to_install_docker](https://user-images.githubusercontent.com/112444/38388353-42afc6b0-38d8-11e8-9b74-d8a4f922fb2d.png)

**Comment by BrianGilbert** [comment]
@rickmanelius had you previously run the packaging script and not deleted the stuff in tmp before updating it yesterday?

**Comment by rfay** [comment]
This was on a windows machine; the packaging script can't be run on Windows, so I don't think that's a problem. The script having trouble here is install_ddev.cmd - on WIndows.

**Comment by BrianGilbert** [comment]
@rfay yes, but if Rick did what I asked when he created the release yesterday it would have kept the old version of docker installers that had been downloaded, causing the version discrepencies

**Comment by rfay** [comment]
You were probably asking the question in the wrong issue I guess @BrianGilbert  - This issue is about failures of the windows install script.

**Comment by BrianGilbert** [comment]
@rfay yes, I'm aware.. but the provided version of docker is based on what happened when the package script was run.

**Comment by BrianGilbert** [comment]
Docker installation removed, user needs to manually install it now, packaging script has option to include installed when building artifact.
