### ISSUE TITLE
Breaks when user has mysql already in the system

### ISSUE THREAD

**Issue by florisvangeel** [drud/quicksprint#42]
when running: start_clean.sh or start_sprint.sh 
```
Network ddev_default is external, skipping 
Failed to start sprint-20180408-2046: Unable to listen on required ports, localhost port 80 is in use,
Troubleshooting suggestions at https://ddev.readthedocs.io/en/latest/users/troubleshooting/#unable-listen 
```
have mariadb running from homebrew on socket.

**Comment by rfay** [comment]
Port 80 is a result of a webserver, not mysql, but the problem is real when somebody has something running on port 80. It's also an easy fix, with the URL given in the error message.

**Comment by joelpittet** [comment]
Maybe it's worth putting this on non-standard ports to avoid this conflict at the sprint?

**Comment by rfay** [comment]
That is worth considering.

**Comment by liberatr** [comment]
I am having an issue where I have some php-fpm listening on port 9000:
> Failed to start sprint-20180409-1042: Unable to listen on required ports, localhost port 9000 is in use

I also think it would be good to add to those instructions, something about re-running the script after you change the config file, just to make it dead-easy for sprinters.

**Comment by liberatr** [comment]
So homebrew had started php-fpm. The solution for me was:
`brew services stop php70`
That command could be different if you have php56 or php71 or something.
You can check with `brew services list`.

**Comment by BrianGilbert** [comment]
@liberatr Just pushed a PR to move the IRC to 9999 instead

@rfay is there any way for us to change the web and db ports if we're not packaging the ddev docker-compose.yaml ?

**Comment by rfay** [comment]
Ports are changed in the config.yaml, not docker-compose. The link in the error message explains it. https://ddev.readthedocs.io/en/latest/users/troubleshooting/#unable-listen

**Comment by BrianGilbert** [comment]
@rfay whats the key to change the DB listening port? That page only lists http server and I can't find any mention of how to in the rest of docs when searching for mysql.

**Comment by rfay** [comment]
The mysql port is a transient port, not fixed, so doesn't matter.

**Comment by florisvangeel** [comment]
perhaps consider a fairly unused port like https://www.speedguide.net/port.php?port=8899   
So we go from Drupal 8 to Drupal 9 in double pase ;).
if people run java stuff its on 8080 and / or 8443

**Comment by rfay** [comment]
@idevit it's totally easy to change ddev port in the .ddev/config.yaml, lots of people do it. So just changing that as needed is good enough for the majority IMO.
