### ISSUE TITLE
Replace 'Press y to continue' with a more common shell script pattern

### ISSUE THREAD

**Issue by joelpittet** [drud/quicksprint#43]
While running we found several times where we wanted to continue that y or anything pattern caught us up.

I'd propose only responding to y or n, or provide the logical default for enter to be y, then you don't need the disclaimer yelling at you for not doing it "right"

> !!You don't need to hit enter!!.

**Comment by rfay** [comment]
I certainly agree, this is pretty unnatural. Just a Y/n accepting an ENTER would be more natural.

**Comment by BrianGilbert** [comment]
PR merged for this
