### ISSUE TITLE
On MacOS, start-clean.sh dies in ddev start

### ISSUE THREAD

**Issue by torenware** [drud/quicksprint#49]
I'm running the DrupalConNA version of the quickstart tarball (release 0.4 I believe).  The install procedure from the MD file works until we get to running ./start-clean.sh for the project.  Looks like we're dying in "ddev start", failing like this:

````
Creating ddev-router
Failed to start sprint-20180409-1415: web service health check timed out
Project is stopped. Run 'ddev start' to start the environment.
Project is stopped. Run 'ddev start' to start the environment.
Project is stopped. Run 'ddev start' to start the environment.
Project is stopped. Run 'ddev start' to start the environment.
Project is stopped. Run 'ddev start' to start the environment.
````

ddev is completely opaque as to what's going on here; there's no log of any kind.  Docker containers, however, are currently running:

````
Robs-MBP-3:sprint-20180409-1415 rtoren$ docker container ls
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS                   PORTS                                                                                                                                      NAMES
fa6c89a19dda        drud/ddev-router:v0.5.0               "/app/docker-entrypo…"   2 minutes ago       Up 2 minutes (healthy)   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:8000->8000/tcp, 0.0.0.0:8025->8025/tcp, 0.0.0.0:8036->8036/tcp, 0.0.0.0:9000->9000/tcp   ddev-router
d5c6d3eaa735        drud/phpmyadmin:v0.2.0                "/run.sh phpmyadmin"     2 minutes ago       Up 2 minutes (healthy)   0.0.0.0:32779->80/tcp                                                                                                                      ddev-sprint-20180409-1415-dba
b18bde71ad4c        briangilbert/cloud9-alpine:20180318   "sh -c '/usr/bin/nod…"   2 minutes ago       Up 2 minutes             0.0.0.0:32778->8000/tcp                                                                                                                    ddev-sprint-20180409-1415-ide
e043f63b2a2d        linuxserver/thelounge:94              "/init"                  2 minutes ago       Up 2 minutes             0.0.0.0:32777->9000/tcp                                                                                                                    ddev-sprint-20180409-1415-irc
81b28065a794        drud/mariadb-local:v0.8.0             "/docker-entrypoint.…"   2 minutes ago       Up 2 minutes (healthy)   0.0.0.0:32776->3306/tcp                                                                                                                    ddev-sprint-20180409-1415-db
````

My guess is that the following container fails to come up, causing the immediate problem:

````
a45d3062ad4a        drud/nginx-php-fpm-local:v1.1.0       "/start.sh"              9 minutes ago       Exited (4) 9 minutes ago
````

Running docker container logs a45d3062ad4a, I get:

````
$ docker container logs a45d3062ad4a  --tail all
+ set -o errexit nounset pipefail
+ DDEV_PHP_VERSION=7.2
+ '[' -n drupal8 ']'
+ export NGINX_DOCROOT=/var/www/html/drupal8
+ NGINX_DOCROOT=/var/www/html/drupal8
+ '[' -f /mnt/ddev_config/nginx-site.conf ']'
+ '[' -n 7.2 ']'
+ update-alternatives --set php /usr/bin/php7.2
+ ln -sf /usr/sbin/php-fpm7.2 /usr/sbin/php-fpm
update-alternatives: using /usr/bin/php7.2 to provide /usr/bin/php (php) in manual mode
+ export PHP_INI=/etc/php/7.2/fpm/php.ini
+ PHP_INI=/etc/php/7.2/fpm/php.ini
+ '[' -d /mnt/ddev_config/php ']'
+ '[' drupal8 = backdrop ']'
+ rm -f /etc/nginx/nginx-site.conf
+ '[' -f /etc/nginx/nginx-site-drupal8.conf ']'
+ ln -s /etc/nginx/nginx-site-drupal8.conf /etc/nginx/nginx-site.conf
+ envsubst '$NGINX_DOCROOT'
+ '[' -n 501 ']'
+ usermod -u 501 nginx
+ '[' -n 20 ']'
+ groupmod -g 20 nginx
groupmod: GID '20' already exists
````

Not sure if "groupmod" has anything to do with the problem, but it is the last item in the log.

**Comment by rfay** [comment]
You have a version of ddev at least two versions ago... How is that happening? This has been fixed since v0.16.0.

**Comment by torenware** [comment]
Apparently there are emails with stale links floating around. I found this link maybe two days ago.  I'll look for a newer release and try that.

Is there a link you're using for the sprints, since what's pointed to by that will be the one that gets downloaded.  Also: I'd try getting it directly via git clone, but it looks like there's some kind of build process required before the sprint instructions will work.

**Comment by torenware** [comment]
@rfay -- do you have a link directing sprinters to do the download. I just cloned release v0.0.6.  If I just naively run ./install-ddev.sh, I get the error:

````
        ####
        # Open Docker preferences, confirm its version 18.03.0 and the memory allocation is set to 3.0 GiB
        # on the Advanced tab, and that docker has fully restarted before continuing.
        #
        # Press y once Docker has restarted, or any other key to exit the script.
        # !!You don't need to hit enter!!.
        #
        ####
        y
Installing docker images for ddev to use...
ls: ddev_tarballs/ddev_docker_images*.tar.xz: No such file or directory
gzip: standard input is a terminal -- ignoring
open /var/lib/docker/tmp/docker-import-272894766/repositories: no such file or directory
````
Clearly, something needs to download or build those tarballs.  So either the instructions are incomplete for the sprinters, or I'm not downloading the right object.  What do I want to be downloading to test this?

**Comment by torenware** [comment]
For purposes of testing, I'm pulling tag v0.0.6 and running package_drupal_script.sh, on the assumption that the resulting build will give me what we're giving to sprinters. Would still like to download from whatever link we're actually giving to sprinters, since we're likely not going to want them to do what I'm doing here.

**Comment by rfay** [comment]
You're doing the right thing, but make sure you've killed off your own ddev before testing. 

When you build, please look at the ddev in the package to make sure it's v0.17.0

I'll be building it shortly as well.

**Comment by torenware** [comment]
Should be dead, dead, dead.  The tarball directory was blown away, and I removed any lingering containers (docker container stop $(docker container ls -q); docker container prune).  The build process just completed.  Notices that it might "take awhile" are accurate :-)

**Comment by rfay** [comment]
I run package_drupal_script.sh with `bash -x package_drupal_script.sh` so I can at least know that it's doing something. Probably a `set -x` at the top of that one would help everybody that has to do it.

**Comment by torenware** [comment]
OK, reading the script clarifies part of the problem. The package gets built into ~/tmp, not into the cloned directory.  I'll see if that object installs appropriately.

**Comment by rfay** [comment]
I should also have mentioned that v0.0.6 of this didn't ever fully work, which is why no packages got pushed up there, so it would help more if you'd test master, or a particular commit on master. Maybe we'll be closer before too long.

**Comment by torenware** [comment]
Happy to test master.  BTW: what state should ./start-clean.sh get the user?  The script did not actually start the containers.  I ran ddev start, and the containers all started, but drupal is not actually installed. It isn't clear what passwords would be required for the DB (I'd probably need to dig to see if there's a docker-compose.yaml file buried somewhere).  If this is the case, the sprinters would need to know what to put into the master install form.

**Comment by rfay** [comment]
DB passwords: `ddev describe`

I'm still a little confused by start_clean.sh but think it should result in a running project.

**Comment by rfay** [comment]
Oh and BTW, master doesn't currently work. Just tried.

**Comment by torenware** [comment]
:-(  Yeah, start_clean.sh don't do dat

I'm working with the package as built in v0.0.6.  Running start_clean.sh is not the ticket. But if you run the commands in the heart of the file, you do end up with a working install:

````
ddev start
ddev exec git fetch
ddev exec git reset --hard origin/8.6.x
ddev exec composer install
ddev exec drush si standard --account-pass=admin --db-url=mysql://db:db@db:3306/db
ddev exec drush cr
ddev describe
````

I'm guessing that one of the error screening lines of the script terminates things prematurely, at least before `drush si` runs.

**Comment by torenware** [comment]
There's a problem at `ddev remove...`.  If the project is not running -- and it won't be when you first run the script -- `ddev remove` will return an error, and the script aborts.  We can certainly handle the error, but I'm not sure that's correct behavior if ddev is not running, but the project has  been built and should be blown away.  But simply handling the error by doing `ddev remove || echo "Removal skipped"` would at least let you get to the actual install.

**Comment by rfay** [comment]
That was already done in a later commit. 
However, the `ddev remove` is superfluous only.

It would be great if you'd move on from v0.0.6

**Comment by torenware** [comment]
Is master healthier?

**Comment by rfay** [comment]
Yes, but I'm testing https://github.com/drud/quicksprint/pull/46, which is master plus a couple of commits for windows. 

I guess I'll try to get a circleci build together tonight; that way we can have a build for every one of these for testing.

**Comment by rfay** [comment]
And @torenware I want to thank you for your enthusiasm to test this. I'm frustrated that it's maturing so slowly and so late. But we'll get there.

**Comment by torenware** [comment]
@rfay -- NP. Yeah, I feel your pain here, since I'd guess you'd rather be drinking beer and listening to bluegrass out there, rather than chase source ghosts :-)  BTW: Just built master and run it. Runs fine on MacOS AFAICT.  We might want to make the script a little more talkative during its progress, since it posts URLs to go to before composer is done composing and the drush install is done installing. But it does come up with a working install w/o any serious errors.  Status Report says that trusted_host_patterns isn't set (which is normal) and that we're not using 8.5.1, which is kinda the point.

**Comment by rfay** [comment]
Nice, thanks! Working on better ways to do this and hopefully it can soon stabilize, and hope you can give it another run.

WHen you don't have to build the main package it is *way* easier to test. But there is the download...

**Comment by torenware** [comment]
Building it for me isn't overhard. I used to set up tests for Rules/D8. Now *that* was hard.

Sorry I'm not set up for Windows testing, which I'm guessing is also going to be an issue. I'm not sure how long it takes to set up CircleCI or Travis for this, but it might be worth it, even though we're only a few days shy of Friday.

Ping me when you want me to give it another go.

**Comment by torenware** [comment]
Ah, I see #50. We're getting there.

**Comment by nearlythere** [comment]
@torenware Interloping on your thread here. You mentioned `Apparently there are emails with stale links floating around` - Eek! 

I am working on improving release communications with the DDEV Newsletter. We're going to get these out on the day of release, so you're the first to know. You can see the latest [here](https://mailchi.mp/8636017d45e5/ddev-local-v017-release-ddev-news) and subscribe (if you're not already!) 

https://mailchi.mp/8636017d45e5/ddev-local-v017-release-ddev-news

I hope that helps!

Also - thanks for jumping in to contribute :D

**Comment by rfay** [comment]
As far as I can tell, this issue is stale, shouldn't be an issue any more. Closing.
