### ISSUE TITLE
Packaging script adds Brian's irc/ide containers into drupal8/.ddev

### ISSUE THREAD

**Issue by mradcliffe** [drud/quicksprint#5]
## Feature Request:

Brian has extra containers as part of the feature set from dev desktop of including an editor, irc client, etc... 

New contributors who do not have an IDE or preferred editor are able to have a nice experience editing files and getting on IRC. We still have and support IRC users (#drupal-contribute has core contributors actively using it to discuss and collaborate), but we are also mentoring during core sprints on Drupal Slack.

I've created the ddev-compatible YAMLs already so I can probably submit a PR.

## What you expected to happen:

* Appropriately named ddev container YAML partials added to .ddev directory.
* Adds .thelounge configuration from BrianGilbert/docksal-core-sprint to this repository.
* Images downloaded
* Images exported and added to ddev images or as a separate tarball.
   * The install scripts would need to be updated in the latter case.

**Comment by mradcliffe** [comment]
I think the main complexity here is the implementation of either modifying the ddev_images tarball to keep all images in the same place.

**Comment by rfay** [comment]
I don't think the ddev_docker_images tarball has to be the only tarball. There can be more than one. The ddev_docker_images tarball comes from the build process on Circle. The images for other things can come from elsewhere.

**Comment by rickmanelius** [comment]
A question that was raised while sitting with @mradcliffe at Midcamp. We are not presuming this repo to be the source of truth and we've reached out to @briangilbert to see if it makes sense to pull in any his work here or have this work pulled out to his repo. Just noting this as something while we keep working in this sandbox! And that might affect whether or not we proceed here. @mradcliffe looks like he has working yml files and it doesn't harm us to get them in here as well.

**Comment by mradcliffe** [comment]
Brian mentioned on 2018.03.11 that probably not this repo, but he wanted to catch up in the morning (2018.03.12 for him) and talk further. So that's probably around 15:00 CST 2018.03.11.

**Comment by BrianGilbert** [comment]
I'm happy to contribute here, After talking to @rfay it seems like a fair bit of what I have been working on is already done here..  there are some pretty big savings in file size that can be made though.. I will open a separate ticket about that.

**Comment by rickmanelius** [comment]
Excellent! Ultimately, whatever helps set us best up for Drupalcon NA is what works for me. If this needs to have a separate home after, more than open to discuss what makes sense.

**Comment by rfay** [comment]
Just responding to the title here "Packaging script adds Brian's irc/ide containers into drupal8/.ddev" - we would *not* want to put any containers into .ddev; we load them into docker via `docker load`. Additional images can be added to a new tarball of images, and loaded (optionally?) on install.

**Comment by mradcliffe** [comment]
This was completed in #12
