### ISSUE TITLE
Windows PowerShell shows many characters like [33m and [0m when running the start_clean.cmd

### ISSUE THREAD

**Issue by geerlingguy** [drud/quicksprint#55]
See screenshot:

![image](https://user-images.githubusercontent.com/481677/38589082-b4439e54-3cee-11e8-95e3-6ceefcd0cdda.png)

(I didn't see an open issue for this, but thought I'd bring it up.)

**Comment by geerlingguy** [comment]
I have not tested whether this is the case also in Cmder, or if it's just PowerShell. But maybe just disable colors in the console if it's on Windows?

**Comment by geerlingguy** [comment]
Ah, this is actually a ddev thing—see https://github.com/drud/ddev/issues/363

**Comment by rfay** [comment]
This was resolved in https://github.com/drud/ddev/pull/795
