### ISSUE TITLE
import-db failed on Windows 10 Pro, Docker ToolBox

### ISSUE THREAD

**Issue by mradcliffe** [drud/quicksprint#6]
**Note that this can be closed if not doing database imports per #3.**

## What happened (or feature request):

Running ddev_start.cmd, the import-db command failed to install the database because it couldn't find the sql file.

1. Using Docker QuickStart Terminal (i.e. Git Bash)
```
C:\Users\username\Desktop\drupal_sprint_package\drupal8>ddev import-db --src=.db_dumps/d8_installed_db.sql.gz
[0mcat: can't open '/db/*.sql': No such file or directory[0m
```

PowerShell wasn't an option to test here because docker commands can only be run in Docker QuickStart Terminal when using Docker ToolBox.

## What you expected to happen:

Database import.

## How to reproduce this:

Windows 10 Pro
Docker ToolBox

## Version

- drupal_sprint_package 0.0.2

**Comment by rfay** [comment]
The biggest problem is that docker toolbox doesn't yet work and may not. It's absolutely not supported at this time.

**Comment by rfay** [comment]
I'm closing this for now, as we have an open issue for support of Docker Toolbox, https://github.com/drud/ddev/issues/636
