### ISSUE TITLE
Remove IRC container

### ISSUE THREAD

**Issue by BrianGilbert** [drud/quicksprint#61]
I was originally directed to include this but given only 1 person at the First Time Sprinters workshop is known to have used it, it would be much more economical for them to use irccloud or https://webchat.freenode.net/

**Comment by mradcliffe** [comment]
Agreed. https://drupal.org/chat shows new contributors how to connect to the various platforms.

**Comment by rfay** [comment]
This was removed in https://github.com/drud/quicksprint/pull/62
