### ISSUE TITLE
Feature - generate database dump in packaging script

### ISSUE THREAD

**Issue by mradcliffe** [drud/quicksprint#7]
The database dump should be as up-to-date as possible with the latest Drupal core branch development so that there are no entity or database updates necessary. Core development in pre-release (pre-alpha) may have entity schema changes that are not stable or experimental.

Something like `ddev exec drush sql-dump --gzip --result-file=/some/path/to/dump.sql` or something? result-file probably needs to be the container volume, and then copied from there into .db_dumps?

**Comment by rfay** [comment]
Good point, makes sense. Maybe the builder script should do a drush si and dump the result.

**Comment by mradcliffe** [comment]
Closing. Brian implemented this.
