### ISSUE TITLE
Git for Windows package gitconfig or tell the user what to do?

### ISSUE THREAD

**Issue by mradcliffe** [drud/quicksprint#83]
If we bundle Git for Windows 2.18.0, then we would probably need to tell users the correct install options to make their lives easier when generating patches (or maybe ship a .gitconfig that specifies the correct behavior).

As I write this up, I think that it makes the most sense to configure the Drupal repository during package build, and then we don't need to worry about global preferences the user sets during the Git for Windows installer.

**Comment by rfay** [comment]
It's my opinion that `git config --global core.autocrlf false` and `git config --global core.eol lf` is the right thing for Windows users. I've spent quite a bit of time on Windows in the last year and find that it doesn't make sense for git to *ever* be converting anything. And all modern editors on Windows are capable of using linefeeds for their line endings.  Drupal 8 specifies this behavior in the [editorconfig](https://cgit.drupalcode.org/drupal/tree/.editorconfig) as well.
