### ISSUE TITLE
Windows versions string in install.sh should support 7, 8 in addition to 10

### ISSUE THREAD

**Issue by mradcliffe** [drud/quicksprint#91]
We check for MINGW64-NT-10.0 but should also check for MINGW64-NT-6.3 (Win 8) and whatever the string is for Win 7 because Win 7 should work fine with Docker Toolbox.

**Comment by mradcliffe** [comment]
Aside from verbose tar errors in sprint.sh (ignored unknown extended header keyword), Windows 8 has been working fine.

**Comment by rfay** [comment]
I have never ever tested ddev on pre-Windows 7...  I wouldn't object! bash has some decent regex parsing stuff.
