### ISSUE TITLE
Windows: package_drupal_script fails

### ISSUE THREAD

**Issue by mradcliffe** [drud/quicksprint#97]
Creating a new issue branched from #96 to address buildkite issues on Windows.

From my manual testing so far I ran into the following issues:

- [ ] jq missing
- [ ] zip missing

**Comment by rfay** [comment]
Sorry to waste your time on something that I could have pointed you to. Please use the setup instructions in https://github.com/drud/ddev/blob/master/docs/developers/buildkite-testmachine-setup.md to get a testable situation.

**Comment by rfay** [comment]
With retries, this is working, but we may have a misbehaving (or misconfigured testbot). While we're working on this in coming days we ought to be able to sort that out. Closing for now.
